# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LangTrans.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pyttsx3
import speech_recognition as sr
import googletrans

from PyQt5 import QtCore, QtGui, QtWidgets
from googletrans import Translator

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(988, 461)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 991, 461))
        self.label.setStyleSheet("background-image: url(:/newPrefix/LangTrans.jpg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/LangTrans.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(20, 230, 311, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 290, 201, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_3.setGeometry(QtCore.QRect(20, 390, 256, 41))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(730, 400, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.speaking)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(840, 400, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        self.pushButton_2.clicked.connect(self.textBrowser_3.clear)
        self.pushButton_2.clicked.connect(self.textBrowser_2.clear)
        self.pushButton_2.clicked.connect(self.textBrowser.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def speaking(self,r):

        engine = pyttsx3.init('sapi5')
        voices = engine.getProperty('voices')
        engine.setProperty('voice', voices[1].id)

        def speak(audio):
            engine.say(audio)
            engine.runAndWait()
    
        r = sr.Recognizer()
    
        with sr.Microphone() as source:
            speak("Welcome to easy language translator")
            speak("Speak something in english")
            print("Listening...")
            r.pause_threshold = 1
            audio = r.listen(source)

        try:
            print("Recognizing...")    
            query = r.recognize_google(audio, language='en-in')
            speak("In which Language do you want to convert")
            self.textBrowser.setText(query)
            self.language(r, query)

        except Exception as e:
            print(e)  
            speak("Unable to recognize your voice please try again")  
            self.textBrowser.setText("Unable to Recognize your voice.") 
            self.textBrowser_2.setText("Please try again !!") 
            return "None"

    def language(self, r, query):
        trans = Translator()

        engine = pyttsx3.init('sapi5')
        voices = engine.getProperty('voices')
        engine.setProperty('voice', voices[1].id)

        def speak(audio):
            engine.say(audio)
            engine.runAndWait()
    
        r = sr.Recognizer()
    
        with sr.Microphone() as source:
            print("Listening...")
            r.pause_threshold = 1
            audio = r.listen(source)

            speech = query

            try:
                print("Recognizing...")    
                query1 = r.recognize_google(audio, language='en-in')
                self.textBrowser_2.setText(query1)
                query1=query1.lower()

                if query1=='spanish':
                    try:
                        result = trans.translate(speech, src='auto', dest="es")
                        con_sen = result.text
                        self.textBrowser_3.setText(con_sen)

                    except Exception as e:
                        print(e)
                        speak("Unable to translate")

                elif query1=='french':
                    try:
                        result = trans.translate(speech, src='auto', dest="fr")
                        con_sen = result.text
                        self.textBrowser_3.setText(con_sen)

                    except Exception as e:
                        print(e)
                        speak("Unable to translate")

                elif query1=='russian':
                    try:
                        result = trans.translate(speech, src='auto', dest="ru")
                        con_sen = result.text
                        self.textBrowser_3.setText(con_sen)

                    except Exception as e:
                        print(e)
                        speak("Unable to translate")

                elif query1=='japanese':
                    try:
                        result = trans.translate(speech, src='auto', dest="ja")
                        con_sen = result.text
                        self.textBrowser_3.setText(con_sen)

                    except Exception as e:
                        print(e)
                        speak("Unable to translate")

                elif query1=='korean':
                    try:
                        result = trans.translate(speech, src='auto', dest="ko")
                        con_sen = result.text
                        self.textBrowser_3.setText(con_sen)

                    except Exception as e:
                        print(e)
                        speak("Unable to translate")

            except Exception as e:
                print(e)  
                speak("Unable to recognize your voice please try again")  
                self.textBrowser.setText("Unable to Recognize your voice.") 
                self.textBrowser_2.setText("Please try again !!") 
                return "None"
    
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Speak"))
        self.pushButton_2.setText(_translate("Form", "Reset"))

import LanTran

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
